DEFAULT: &DEFAULT
  supported_markets:
    equities
  token_expiration_minutes: 999999
  rsa_private_key: 
  firebase:
    base_url: https://renda-facil-681e2-default-rtdb.firebaseio.com/
    auth_token: 
  b3:
    base_url: https://apib3i-cert.b3.com.br:2443/api
    token_url: https://login.microsoftonline.com/4bee639f-5388-44c7-bbac-cb92a93911e6/oauth2/v2.0/token
    token_scope: 0c991613-4c90-454d-8685-d466a47669cb/.default
    auth_url: https://b3Investidorcer.b2clogin.com/b3Investidorcer.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_FINTECH&client_id=eb4332cb-8de6-4321-b6ee-bc383c813cbd&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fwww.investidor.b3.com.br&scope=openid&response_type=code&prompt=login
    api_path:
      movements: /b3i/movement
      health: /acesso/healthcheck
    auth:
      client_id: $B3_AUTH_CLIENT_ID|
      client_secret: $B3_AUTH_CLIENT_SECRET|
    certificate:
      cert: $B3_CERTIFICATE_CERT|
      key: $B3_CERTIFICATE_KEY|
      pw: $B3_CERTIFICATE_PW|

DEV:
  <<: *DEFAULT

CERT:
  <<: *DEFAULT
  token_expiration_minutes: 60

PROD:
  <<: *DEFAULT
  token_expiration_minutes: 60
  b3:
    base_url: https://investidor.b3.com.br:2443
    token_url: https://login.microsoftonline.com/aa5ac705-873b-4afc-a29d-f0adb89ccf5c/oauth2/v2.0/token
    token_scope: abae5dfa-65e6-47c1-82ec-a54a8a3213b9/.default